{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "skill-wanderer.labels" . | nindent 4 }}
type: Opaque
data: {}
  # Note: Secret data should be created manually or through external secret management
  # This template creates an empty secret that needs to be populated with actual values
  # Use kubectl to create the secret with actual values:
  # kubectl create secret generic skill-wanderer-secrets \
  #   --from-literal=NUXT_PUBLIC_FIREBASE_API_KEY="your-api-key" \
  #   --from-literal=NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN="your-auth-domain" \
  #   --from-literal=NUXT_PUBLIC_FIREBASE_PROJECT_ID="your-project-id" \
  #   --from-literal=NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET="your-storage-bucket" \
  #   --from-literal=NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="your-sender-id" \
  #   --from-literal=NUXT_PUBLIC_FIREBASE_APP_ID="your-app-id" \
  #   --from-literal=NUXT_PUBLIC_MEASUREMENT_ID="your-measurement-id"
{{- end }}
