replicaCount: 1

image:
  repository: ghcr.io/jimmyyouhei/skill-wanderer-landing-page
  pullPolicy: Always
  tag: "latest"  # Default to latest, override in production

# Secret configuration for environment variables
secret:
  enabled: true
  name: "skill-wanderer-secrets"
  # Environment variables will be loaded from the secret
  envKeys:
    - NUXT_PUBLIC_FIREBASE_API_KEY
    - NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    - NUXT_PUBLIC_FIREBASE_PROJECT_ID
    - NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET
    - NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
    - NUXT_PUBLIC_FIREBASE_APP_ID
    - NUXT_PUBLIC_MEASUREMENT_ID

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: skill-wanderer.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}